# Lightweight docker-compose which only has the datastores, so you can still develop rails locally

# To use, run docker-compose up -d
version: '3.4'

services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  solr:
    image: solr:6.6
    ports:
      - '8983:8983'
    volumes:
      - solr-data:/opt/solr/server/solr/mycores
      - ./solr/config:/config
      - ./solr/scripts/solr-precreate-jupiter.sh:/docker-entrypoint-initdb.d/solr-precreate-jupiter.sh

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  postgres-data:
  solr-data:
